export const APP_FIRST_LOAD = "APP/FIRST_LOAD";
export const APP_SET_CURRENT_PAGE = "APP/SET_CURRENT_PAGE";

export const POST_FETCH_DATA_START = "POST/FETCH_DATA_START";
export const POST_FETCH_DATA_SUCCESS = "POST/FETCH_DATA_SUCCESS";
export const POST_FETCH_DATA_FAILURE = "POST/FETCH_DATA_FAILURE";
